server:
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pryton-bot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pryton-bot
          app: pryton-bot
          __path__: /var/log/pryton/*.log

    relabel_configs:
      - source_labels: [__path__]
        regex: '.+\.log\.(zip|gz|[0-9]+)$'
        action: drop

    pipeline_stages:
      # Парсим строку лога
      - regex:
          expression: '^(?P<utc_timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \| (?P<level>\w+) \| (?P<message>.*)'
      
      # Парсим как UTC время
      - timestamp:
          source: utc_timestamp
          format: "2006-01-02 15:04:05"
          location: "UTC"
      
      # Добавляем лейблы
      - labels:
          level: