global:
  resolve_timeout: 5m

route:
  receiver: telegram-admins
  group_wait:     30s
  group_interval: 5m
  repeat_interval: 2h

receivers:
- name: telegram-admins
  webhook_configs:
    - url: 'http://bot:8001/alert'
      send_resolved: true
