"""Add settings tables and update game model

Revision ID: 31befa8b428e
Revises: bcb30bebfffe
Create Date: 2025-05-30 10:00:21.343874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31befa8b428e'
down_revision = 'bcb30bebfffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_participants', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.drop_column('game_participants', 'created_at')
    op.add_column('games', sa.Column('max_drivers', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('max_seekers', sa.Integer(), nullable=True))
    op.alter_column('games', 'max_participants',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'max_participants',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('games', 'max_seekers')
    op.drop_column('games', 'max_drivers')
    op.add_column('game_participants', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('game_participants', 'joined_at')
    # ### end Alembic commands ### 