"""add_game_zone_fields

Revision ID: 37c55e0a72e4
Revises: b3376efa55a3
Create Date: 2025-05-30 14:51:46.019085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c55e0a72e4'
down_revision = 'b3376efa55a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('zone_center_lat', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('zone_center_lon', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('zone_radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'zone_radius')
    op.drop_column('games', 'zone_center_lon')
    op.drop_column('games', 'zone_center_lat')
    # ### end Alembic commands ### 