"""settings

Revision ID: 37ceda1dbf28
Revises: 5b18ce3bad4d
Create Date: 2025-06-02 23:28:16.352030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ceda1dbf28'
down_revision = '5b18ce3bad4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_settings', sa.Column('auto_start_game', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('auto_start_hiding', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('auto_start_searching', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('auto_assign_roles', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('auto_end_game', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('hiding_phase_duration', sa.Integer(), nullable=True))
    op.add_column('game_settings', sa.Column('searching_phase_duration', sa.Integer(), nullable=True))
    op.add_column('game_settings', sa.Column('game_start_notification_time', sa.Integer(), nullable=True))
    op.add_column('game_settings', sa.Column('manual_control_mode', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('notify_on_role_assignment', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('notify_on_phase_change', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('notify_on_participant_action', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('allow_early_start', sa.Boolean(), nullable=True))
    op.add_column('game_settings', sa.Column('min_participants_to_start', sa.Integer(), nullable=True))
    op.drop_column('game_settings', 'hiding_time')
    op.drop_column('game_settings', 'admin_manual_control')
    op.drop_column('game_settings', 'auto_reminders')
    op.drop_column('game_settings', 'is_default')
    op.drop_column('game_settings', 'search_time')
    op.drop_column('game_settings', 'is_active')
    op.drop_column('game_settings', 'auto_start_enabled')
    op.drop_column('game_settings', 'auto_phase_transition')
    op.drop_column('game_settings', 'auto_game_completion')
    op.drop_column('game_settings', 'reminder_times')
    op.drop_column('game_settings', 'auto_end_when_all_found')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_settings', sa.Column('auto_end_when_all_found', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('reminder_times', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('auto_game_completion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('auto_phase_transition', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('auto_start_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('search_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('auto_reminders', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('admin_manual_control', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_settings', sa.Column('hiding_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('game_settings', 'min_participants_to_start')
    op.drop_column('game_settings', 'allow_early_start')
    op.drop_column('game_settings', 'notify_on_participant_action')
    op.drop_column('game_settings', 'notify_on_phase_change')
    op.drop_column('game_settings', 'notify_on_role_assignment')
    op.drop_column('game_settings', 'manual_control_mode')
    op.drop_column('game_settings', 'game_start_notification_time')
    op.drop_column('game_settings', 'searching_phase_duration')
    op.drop_column('game_settings', 'hiding_phase_duration')
    op.drop_column('game_settings', 'auto_end_game')
    op.drop_column('game_settings', 'auto_assign_roles')
    op.drop_column('game_settings', 'auto_start_searching')
    op.drop_column('game_settings', 'auto_start_hiding')
    op.drop_column('game_settings', 'auto_start_game')
    # ### end Alembic commands ### 