"""add_scheduled_notifications_table

Revision ID: 6326065552ed
Revises: 31befa8b428e
Create Date: 2025-05-30 12:42:54.183488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6326065552ed'
down_revision = '31befa8b428e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 