"""photo and game phase improve

Revision ID: 9a46a16aee21
Revises: d93b10419307
Create Date: 2025-06-02 22:07:13.851231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a46a16aee21'
down_revision = 'd93b10419307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_participants', sa.Column('has_hidden', sa.Boolean(), nullable=True))
    op.add_column('game_participants', sa.Column('hidden_at', sa.DateTime(), nullable=True))
    op.add_column('photos', sa.Column('photo_type', sa.Enum('HIDING_SPOT', 'FOUND_CAR', name='phototype'), nullable=False))
    op.add_column('photos', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('photos', sa.Column('found_driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['found_driver_id'], ['id'])
    op.create_foreign_key(None, 'photos', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'found_driver_id')
    op.drop_column('photos', 'reviewed_at')
    op.drop_column('photos', 'approved_by')
    op.drop_column('photos', 'photo_type')
    op.drop_column('game_participants', 'hidden_at')
    op.drop_column('game_participants', 'has_hidden')
    # ### end Alembic commands ### 