"""create_scheduled_events_table

Revision ID: b3376efa55a3
Revises: 6532ea8d0882
Create Date: 2025-05-30 13:17:13.511997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3376efa55a3'
down_revision = '6532ea8d0882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_notifications_id', table_name='scheduled_notifications')
    op.drop_table('scheduled_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_type', postgresql.ENUM('REMINDER_60MIN', 'REMINDER_24MIN', 'REMINDER_5MIN', 'GAME_START', 'HIDING_END', 'GAME_CANCELLED', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scheduler_job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='scheduled_notifications_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduled_notifications_pkey')
    )
    op.create_index('ix_scheduled_notifications_id', 'scheduled_notifications', ['id'], unique=False)
    # ### end Alembic commands ### 