"""add_district_zones_table

Revision ID: d93b10419307
Revises: 37c55e0a72e4
Create Date: 2025-05-30 15:05:35.714406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93b10419307'
down_revision = '37c55e0a72e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 