global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'pryton_bot'
    static_configs:
      - targets: ['bot:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

rule_files:
  - /etc/prometheus/rules/alerts.yaml